DROP DATABASE IF EXISTS BROAD;

CREATE DATABASE BROAD;

USE BROAD;

DROP TABLE IF EXISTS `VIEW`;

CREATE TABLE `VIEW` (
	`VW_KEY`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`VW_PG_KEY`	CHAR(6)	NOT NULL,
	`VW_WE_KEY`	INT	NOT NULL
);

DROP TABLE IF EXISTS `BROADTIME`;

CREATE TABLE `BROADTIME` (
	`BT_NUM`		INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`BT_VW_KEY`		INT	NOT NULL,
	`BT_DATE`		DATE NOT	NULL,
	`BT_TIMETABLE`	TIME NOT	NULL,
    `BT_ENDTIME`	TIME NOT	NULL
);

DROP TABLE IF EXISTS `WEEK`;

CREATE TABLE `WEEK` (
	`WE_KEY`	INT PRIMARY KEY	NOT NULL,
	`WE_NAME`	CHAR(3) NOT NULL
);

DROP TABLE IF EXISTS `PROGRAM`;

CREATE TABLE `PROGRAM` (
	`PG_KEY`	VARCHAR(6) PRIMARY KEY	NOT NULL,
	`PG_NAME`	VARCHAR(20) NOT	NULL,
	`PG_AGE`	ENUM("ALL","12세","15세","19세") DEFAULT "ALL" NOT	NULL,
	`PG_NUM` 	INT NOT NULL,
	`PG_TIME`	VARCHAR(6) NOT	NULL,
    `PG_CH_NAME` VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
	`US_KEY`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`US_ID`	VARCHAR(20) UNIQUE NOT NULL,
	`US_PW`	VARCHAR(20) NOT NULL,
	`US_NAME`	VARCHAR(10) NOT NULL,
	`US_AUTHORITY`	ENUM("ADMIN","USER") DEFAULT "USER" NOT	NULL
);

DROP TABLE IF EXISTS `GENRE`;

CREATE TABLE `GENRE` (
	`GR_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`GR_NAME`	VARCHAR(10) NOT	NULL
);

DROP TABLE IF EXISTS `INDEX`;

CREATE TABLE `INDEX` (
	`IN_KEY`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`IN_PG_KEY`	CHAR(6)	NOT NULL,
	`IN_US_KEY`	INT NOT NULL
);

DROP TABLE IF EXISTS `PROGRAMGENRE`;

CREATE TABLE `PROGRAMGENRE` (
	`PR_KEY`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`PR_GR_NUM`	INT	NOT NULL,
	`PR_PG_KEY`	VARCHAR(6)	NOT NULL
);

DROP TABLE IF EXISTS `CHANNEL`;

CREATE TABLE `CHANNEL` (
	`CH_NAME`	VARCHAR(10) PRIMARY KEY NOT NULL
	
	
);


DELIMITER //
CREATE TRIGGER before_insert_program
BEFORE INSERT ON PROGRAM
FOR EACH ROW
BEGIN
    DECLARE next_num INT;
    SELECT COALESCE(MAX(CAST(SUBSTRING(PG_KEY, 4, 3) AS UNSIGNED)), 0) + 1
    INTO next_num FROM PROGRAM WHERE PG_CH_NAME = NEW.PG_CH_NAME;
    
    SET NEW.PG_NUM = next_num;
    SET NEW.PG_KEY = CONCAT(NEW.PG_CH_NAME, LPAD(next_num, 3, '0'));
END //
DELIMITER ;

ALTER TABLE `VIEW` ADD CONSTRAINT `FK_PROGRAM_TO_VIEW_1` FOREIGN KEY (
	`VW_PG_KEY`
)
REFERENCES `PROGRAM` (
	`PG_KEY`
);

ALTER TABLE `VIEW` ADD CONSTRAINT `FK_WEEK_TO_VIEW_1` FOREIGN KEY (
	`VW_WE_KEY`
)
REFERENCES `WEEK` (
	`WE_KEY`
);

ALTER TABLE `BROADTIME` ADD CONSTRAINT `FK_VIEW_TO_BROADTIME_1` FOREIGN KEY (
	`BT_VW_KEY`
)
REFERENCES `VIEW` (
	`VW_KEY`
);

ALTER TABLE `PROGRAM` ADD CONSTRAINT `FK_CHANNEL_TO_PROGRAM_1` FOREIGN KEY (
	`PG_CH_NAME`
)
REFERENCES `CHANNEL` (
	`CH_NAME`
);

ALTER TABLE `INDEX` ADD CONSTRAINT `FK_PROGRAM_TO_INDEX_1` FOREIGN KEY (
	`IN_PG_KEY`
)
REFERENCES `PROGRAM` (
	`PG_KEY`
);

ALTER TABLE `INDEX` ADD CONSTRAINT `FK_USER_TO_INDEX_1` FOREIGN KEY (
	`IN_US_KEY`
)
REFERENCES `USER` (
	`US_KEY`
);

ALTER TABLE `PROGRAMGENRE` ADD CONSTRAINT `FK_GENRE_TO_PROGRAMGENRE_1` FOREIGN KEY (
	`PR_GR_NUM`
)
REFERENCES `GENRE` (
	`GR_NUM`
);

ALTER TABLE `PROGRAMGENRE` ADD CONSTRAINT `FK_PROGRAM_TO_PROGRAMGENRE_1` FOREIGN KEY (
	`PR_PG_KEY`
)
REFERENCES `PROGRAM` (
	`PG_KEY`
);

INSERT INTO USER (US_ID, US_PW, US_NAME, US_AUTHORITY) VALUES
('admin01', 'pass1234', '관리자', 'ADMIN'),
('user01', 'userpass', '홍길동', 'USER'),
('user02', 'mypassword', '김철수', 'USER');

INSERT INTO CHANNEL (CH_NAME) VALUES
('KBS'),
('SBS'),
('MBC');

INSERT INTO PROGRAM (PG_NAME, PG_AGE, PG_TIME, PG_CH_NAME) VALUES
('뉴스9', 'ALL', '21:00', 'KBS'),
('드라마A', '15세', '22:00', 'SBS'),
('예능B', '12세', '19:00', 'MBC');

INSERT INTO WEEK (WE_KEY, WE_NAME) VALUES
(1, "월요일"), (2, "화요일"), (3, "수요일"),
(4, "목요일"), (5, "금요일"), (6, "토요일"),
(7, "일요일");

INSERT INTO VIEW (VW_PG_KEY, VW_WE_KEY) VALUES
("KBS001", 1);

INSERT INTO BROADTIME (BT_VW_KEY, BT_DATE, BT_TIMETABLE, BT_ENDTIME) VALUES
(1,NOW(),"19:30:00","21:03:04");

INSERT INTO `INDEX` (IN_PG_KEY, IN_US_KEY) VALUES
("MBC001", 1);

INSERT INTO GENRE (GR_NAME) VALUES
("예능"), ("시사"), ("드라마"), ("영화");

INSERT INTO PROGRAMGENRE (PR_PG_KEY, PR_GR_NUM) VALUES
("KBS001", 1);

SELECT * FROM PROGRAMGENRE; # 프로시저를 통해 1번은 예능 2번은 시사 이런식..
SELECT p.PG_NAME, g.GR_NAME, w.WE_name
FROM PROGRAM p
JOIN PROGRAMGENRE pg ON p.PG_KEY = pg.PR_PG_KEY
JOIN GENRE g ON pg.PR_GR_NUM = g.GR_NUM
JOIN `VIEW` v ON p.PG_KEY = v.VW_PG_KEY
JOIN WEEK w ON v.VW_WE_KEY = w.WE_KEY
WHERE g.GR_NAME = '예능' AND p.PG_CH_NAME = 'KBS' AND w.WE_name = '월요일';